### ISSUE TITLE
Uncaught ReferenceError: require is not defined  

### ISSUE THREAD

**Issue by Jawad-Ali2** [ed-roh/react-ecommerce#6]
![image](https://github.com/ed-roh/react-ecommerce/assets/107391644/55f70c75-b2f9-4ef5-b8ab-feee9d952f2a)

VS CODE: 
![image](https://github.com/ed-roh/react-ecommerce/assets/107391644/f493b8b4-fd3e-4e94-b183-1c5e31222174)

**Comment by vineet-op** [comment]
manually Import the images by import keyword one by one, 
or if you got another way feel free to tell
